name: Compress Images

on:
  push:
    paths:
      - 'images/**'  # imagesフォルダ以下の画像が変更されたら実行
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: ImageMagickをインストール
        run: sudo apt-get install -y imagemagick

      - name: JPEGとPNGを圧縮 & WebPに変換
        run: |
          find images -type f \( -iname "*.jpg" -o -iname "*.jpeg" \) -exec mogrify -strip -quality 85% {} +
          find images -type f -iname "*.png" -exec mogrify -strip -quality 85% {} +
          find images -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) -exec sh -c 'cwebp -q 85 "$1" -o "${1%.*}.webp"' _ {} \;

      - name: 圧縮後のファイルをコミット & プッシュ
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images
          git commit -m "Auto-compressed images"
          git push
        continue-on-error: true
