name: Compress Images (Without WebP & Remove WebP)

on:
  push:
    paths:
      - 'images/**'  # imagesフォルダ以下の画像が変更されたら実行
    branches:
      - main

jobs:
  compress:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: ImageMagickをインストール
        run: sudo apt-get install -y imagemagick

      - name: JPEGとPNGを圧縮
        run: |
          # JPEG圧縮 (品質85%)
          find images -type f -iname "*.jpg" -o -iname "*.jpeg" -exec mogrify -strip -quality 85% {} +

          # PNG圧縮 (無損失圧縮)
          find images -type f -iname "*.png" -exec optipng -o7 {} \;

      - name: WebPファイルを削除
        run: |
          # imagesフォルダ内のWebPファイルを削除
          find images -type f -iname "*.webp" -exec rm {} \;

      - name: 圧縮後のファイルをコミット & プッシュ
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add images
          git commit -m "Auto-compressed images and removed WebP files"
          git push
